### ISSUE TITLE
Client queries database every time state changes

### ISSUE THREAD

**Issue by asBrettisay** [JTJTJ-Analytics/clickhover#85]
The client is supposed to cache the user info once when core module boots up. Instead it queries the DB once ever state change, sometimes twice.

**Comment by joe-tohdjojo** [comment]
is this something that you tried to fix with sessions? i think we still have this problem though. i'll look into it some more this weekend

**Comment by asBrettisay** [comment]
Fixed by [1856b73](https://github.com/JTJTJ-Analytics/clickhover/commit/1856b737b5bf1b51ed61979901f34ecbe8f05076)
